/**
 * Records when every component source file was first added and last changed, so
 * the docs can badge recent work. Run through `bun run docs:dates`; the web
 * build runs it too, which keeps the badges honest on every deploy.
 *
 * Dates come from git rather than a hand-kept list: a component's history is
 * already the truth, and nobody has to remember to update anything.
 */
import { execFileSync } from "node:child_process"
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(scriptDir, "../../..")
const componentsDir = join(repoRoot, "packages/ui/src/components")
const outputFile = resolve(
  scriptDir,
  "../src/docs/components/dates.generated.ts"
)

function git(args: string[]) {
  return execFileSync("git", args, {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim()
}

/** Committer dates, oldest last, as `YYYY-MM-DD`. */
function commitDates(path: string, extraArgs: string[] = []) {
  return git(["log", "--follow", "--format=%cs", ...extraArgs, "--", path])
    .split("\n")
    .filter((line) => line.length > 0)
}

function collect() {
  const dates: Record<string, { added: string; updated: string }> = {}

  for (const entry of readdirSync(componentsDir).sort()) {
    if (!entry.endsWith(".tsx")) continue

    const name = entry.slice(0, -".tsx".length)
    const path = `packages/ui/src/components/${entry}`
    // The oldest add wins: `--follow` reports one per rename in the chain.
    const added = commitDates(path, ["--diff-filter=A"]).at(-1)
    const updated = commitDates(path).at(0)

    // A file that has never been committed has no history to report.
    if (!added || !updated) continue

    dates[name] = { added, updated }
  }

  return dates
}

/** Quoted only when it has to be, so the output survives Prettier untouched. */
function key(name: string) {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : `"${name}"`
}

function serialize(dates: Record<string, { added: string; updated: string }>) {
  const entries = Object.entries(dates)
    .map(
      ([name, { added, updated }]) =>
        `  ${key(name)}: { added: "${added}", updated: "${updated}" },`
    )
    .join("\n")

  return `// Generated by apps/web/scripts/generate-component-dates.ts.
// Do not edit by hand; run \`bun run docs:dates\` instead.

export type ComponentDates = {
  /** Committer date of the commit that added the file, as YYYY-MM-DD. */
  added: string
  /** Committer date of the most recent commit touching the file. */
  updated: string
}

export const componentDates: Record<string, ComponentDates> = {
${entries}
}
`
}

function main() {
  let contents: string
  try {
    contents = serialize(collect())
  } catch (error) {
    // Without git history there is nothing to regenerate, and the committed
    // file is still better than failing the build.
    console.warn(
      `[docs:dates] skipped: ${error instanceof Error ? error.message : String(error)}`
    )
    return
  }

  let previous = ""
  try {
    previous = readFileSync(outputFile, "utf8")
  } catch {
    previous = ""
  }

  if (previous === contents) {
    console.log("[docs:dates] up to date")
    return
  }

  writeFileSync(outputFile, contents)
  console.log("[docs:dates] wrote src/docs/components/dates.generated.ts")
}

main()
