// Builds dist/tokens.css — the palette on its own, scoped to a class.
//
// WHY THIS EXISTS, when globals.css and styles.css already carry the tokens:
// both of those declare them on `:root`. That is right for an app this design
// system themes, and wrong for an app that only *hosts* a few of its
// components and owns some of the same names — `--background`, `--muted`,
// `--primary` are shadcn's, not ours — where putting ours on `:root` would
// repaint the host.
//
// So this emits the same values under `.cx-theme`. Custom properties inherit,
// so wrapping a subtree in that class gives the components inside it our
// palette and leaves the rest of the page alone.
//
// It carries no utilities, only tokens, so a host compiles nothing of ours: it
// maps these variables in its own config.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(here, "..")

const src = readFileSync(resolve(pkgRoot, "src/styles/globals.css"), "utf8")

/** The body of a top-level `selector { … }` block, brace-counted. */
function block(css, selector) {
  const start = css.indexOf(selector + " {")
  if (start === -1) throw new Error(`build-tokens: no \`${selector}\` block.`)
  let depth = 0
  for (let i = css.indexOf("{", start); i < css.length; i++) {
    if (css[i] === "{") depth++
    else if (css[i] === "}" && --depth === 0)
      return css.slice(css.indexOf("{", start) + 1, i)
  }
  throw new Error(`build-tokens: \`${selector}\` block is unterminated.`)
}

/**
 * Custom-property declarations sitting directly in the block — no utilities,
 * and nothing from a nested rule. A nested declaration is scoped to whatever
 * selector holds it; hoisting it flat would apply it to the whole theme.
 */
function declarations(body) {
  const out = []
  let depth = 0
  for (const m of body.matchAll(/[{}]|(--[a-z0-9-]+)\s*:\s*([^;{}]+);/gi)) {
    if (m[0] === "{") depth++
    else if (m[0] === "}") depth--
    else if (depth === 0) {
      out.push(`  ${m[1]}: ${m[2].trim().replace(/\s*\n\s*/g, " ")};`)
    }
  }
  if (out.length === 0) throw new Error("build-tokens: extracted no tokens.")
  return out.join("\n")
}

const light = declarations(block(src, ":root"))
const dark = declarations(block(src, ".dark"))

const out = `/*
 * @carsxe/design-system — palette only, scoped to \`.cx-theme\`.
 * GENERATED by scripts/build-tokens.mjs. Do not edit.
 *
 * For an app this design system themes, import globals.css (Tailwind v4) or
 * styles.css (prebuilt) instead — those put the palette on :root.
 *
 * Use this one when the host page has its own palette and only some subtree
 * should be ours:
 *
 *   import "@carsxe/design-system/tokens.css"
 *   <div className="cx-theme"> … design system components … </div>
 *
 * These are plain hex, so a host maps them without hsl(), e.g.
 *   colors: { popover: "var(--popover)", accent: "var(--accent)" }
 */

.cx-theme {
${light}
}

/* Both shapes: the dark class on an ancestor (usual), or on the scope itself. */
.dark .cx-theme,
.cx-theme.dark {
${dark}
}
`

mkdirSync(resolve(pkgRoot, "dist"), { recursive: true })
writeFileSync(resolve(pkgRoot, "dist/tokens.css"), out)
console.log(
  `build-tokens: wrote dist/tokens.css (${light.split("\n").length} light, ${dark.split("\n").length} dark)`
)
