// Builds dist/tokens.css — the palette on its own, scoped to a class.
//
// WHY THIS EXISTS, when globals.css and styles.css already carry the tokens:
// both of those declare them on `:root`, which is right for an app themed by
// this design system and wrong for an app that only *hosts* a few of its
// components. A host with its own palette almost certainly owns some of the
// same names — `--background`, `--muted`, `--primary` are shadcn's, not ours —
// and putting ours on `:root` silently repaints the host.
//
// So this emits the same values under `.cx-theme`. Custom properties inherit,
// so wrapping a subtree in that class gives the components inside it our
// palette and leaves the rest of the page alone.
//
// It carries no utilities, only tokens: a Tailwind v3 host cannot compile our
// v4 stylesheet, but it can map these variables in its own config. That is the
// path for consumers not yet on v4.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(here, "..")

const src = readFileSync(resolve(pkgRoot, "src/styles/globals.css"), "utf8")

/** The body of a top-level `selector { … }` block, brace-counted. */
function block(css, selector) {
  const start = css.indexOf(selector + " {")
  if (start === -1) throw new Error(`build-tokens: no \`${selector}\` block.`)
  let depth = 0
  for (let i = css.indexOf("{", start); i < css.length; i++) {
    if (css[i] === "{") depth++
    else if (css[i] === "}" && --depth === 0)
      return css.slice(css.indexOf("{", start) + 1, i)
  }
  throw new Error(`build-tokens: \`${selector}\` block is unterminated.`)
}

/** Custom-property declarations only — no nested rules, no utilities. */
function declarations(body) {
  const out = []
  for (const m of body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
    out.push(`  ${m[1]}: ${m[2].trim().replace(/\s*\n\s*/g, " ")};`)
  }
  if (out.length === 0) throw new Error("build-tokens: extracted no tokens.")
  return out.join("\n")
}

/**
 * `#eaf5ff` -> `208.57 100% 95.88%`.
 *
 * For hosts whose Tailwind config wraps tokens in `hsl()` — the shadcn v3
 * convention, `hsl(var(--accent))`. Those cannot read a hex token at all:
 * `hsl(#eaf5ff)` is invalid and the declaration is dropped, so the element
 * renders with no colour rather than the wrong one. Two decimal places round
 * trips every colour in the palette exactly.
 */
function hexToHslTriplet(hex) {
  let h = hex.slice(1)
  if (h.length === 3)
    h = h
      .split("")
      .map((c) => c + c)
      .join("")
  const r = parseInt(h.slice(0, 2), 16) / 255
  const g = parseInt(h.slice(2, 4), 16) / 255
  const b = parseInt(h.slice(4, 6), 16) / 255
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const l = (max + min) / 2
  let hue = 0
  let sat = 0
  if (max !== min) {
    const d = max - min
    sat = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    hue =
      max === r
        ? (g - b) / d + (g < b ? 6 : 0)
        : max === g
          ? (b - r) / d + 2
          : (r - g) / d + 4
    hue *= 60
  }
  const round = (v) => Math.round(v * 100) / 100
  return `${round(hue)} ${round(sat * 100)}% ${round(l * 100)}%`
}

/** Only hex values convert. Shadows, rgba(), radii and font stacks pass through. */
function toHslTriplets(declarationBlock) {
  return declarationBlock.replace(
    /(:\s*)(#[0-9a-f]{3}|#[0-9a-f]{6})(;)/gi,
    (_, before, hex, after) => before + hexToHslTriplet(hex) + after
  )
}

const light = declarations(block(src, ":root"))
const dark = declarations(block(src, ".dark"))

const out = `/*
 * @carsxe/design-system — palette only, scoped to \`.cx-theme\`.
 * GENERATED by scripts/build-tokens.mjs. Do not edit.
 *
 * For an app this design system themes, import globals.css (Tailwind v4) or
 * styles.css (prebuilt) instead — those put the palette on :root.
 *
 * Use this one when the host page has its own palette and only some subtree
 * should be ours:
 *
 *   import "@carsxe/design-system/tokens.css"
 *   <div className="cx-theme"> … design system components … </div>
 *
 * Tailwind v3 hosts: these are plain hex, so map them without hsl(), e.g.
 *   colors: { popover: "var(--popover)", accent: "var(--accent)" }
 */

.cx-theme {
${light}
}

/* Both shapes: the dark class on an ancestor (usual), or on the scope itself. */
.dark .cx-theme,
.cx-theme.dark {
${dark}
}
`

const hslOut = `/*
 * @carsxe/design-system — palette only, scoped to \`.cx-theme\`, as HSL triplets.
 * GENERATED by scripts/build-tokens.mjs. Do not edit.
 *
 * Same values as tokens.css, in the shape a shadcn-style Tailwind v3 host
 * already expects: bare \`H S% L%\` for \`hsl(var(--token))\`. Such a host cannot
 * read tokens.css at all — \`hsl(#eaf5ff)\` is invalid — so importing this one
 * instead lets it keep its existing colour config untouched, and opacity
 * modifiers like \`bg-accent/50\` keep working, which hex tokens cannot support.
 *
 * Non-colour tokens (shadows, rgba hairlines, radii) are unchanged, so map
 * those without hsl():
 *   colors: { accent: "hsl(var(--accent))" }
 *   boxShadow: { panel: "var(--panel-shadow)" }
 */

.cx-theme {
${toHslTriplets(light)}
}

/* Both shapes: the dark class on an ancestor (usual), or on the scope itself. */
.dark .cx-theme,
.cx-theme.dark {
${toHslTriplets(dark)}
}
`

mkdirSync(resolve(pkgRoot, "dist"), { recursive: true })
writeFileSync(resolve(pkgRoot, "dist/tokens.css"), out)
writeFileSync(resolve(pkgRoot, "dist/tokens-hsl.css"), hslOut)
console.log(
  `build-tokens: wrote dist/tokens.css and dist/tokens-hsl.css (${light.split("\n").length} light, ${dark.split("\n").length} dark)`
)
