/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsBrandRouteImport } from './routes/docs/brand'
import { Route as DocsComponentsRouteImport } from './routes/docs/components'
import { Route as DocsSkillsRouteImport } from './routes/docs/skills'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsComponentsIndexRouteImport } from './routes/docs/components/index'
import { Route as DocsComponentsSlugRouteImport } from './routes/docs/components/$slug'
import { Route as DocsSkillsIndexRouteImport } from './routes/docs/skills/index'
import { Route as DocsSkillsSlugRouteImport } from './routes/docs/skills/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBrandRoute = DocsBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsRoute = DocsComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsRoute = DocsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DocsRoute,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsIndexRoute = DocsComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsComponentsSlugRoute = DocsComponentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsComponentsRoute,
} as any)
const DocsSkillsIndexRoute = DocsSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsSkillsRoute,
} as any)
const DocsSkillsSlugRoute = DocsSkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsSkillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/docs/brand': typeof DocsBrandRoute
  '/docs/components': typeof DocsComponentsRouteWithChildren
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/$slug': typeof DocsComponentsSlugRoute
  '/docs/skills/$slug': typeof DocsSkillsSlugRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
  '/docs/skills/': typeof DocsSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/og': typeof ApiOgRoute
  '/docs/brand': typeof DocsBrandRoute
  '/docs/theming': typeof DocsThemingRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/$slug': typeof DocsComponentsSlugRoute
  '/docs/skills/$slug': typeof DocsSkillsSlugRoute
  '/docs/components': typeof DocsComponentsIndexRoute
  '/docs/skills': typeof DocsSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/docs/brand': typeof DocsBrandRoute
  '/docs/components': typeof DocsComponentsRouteWithChildren
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/docs/theming': typeof DocsThemingRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/$slug': typeof DocsComponentsSlugRoute
  '/docs/skills/$slug': typeof DocsSkillsSlugRoute
  '/docs/components/': typeof DocsComponentsIndexRoute
  '/docs/skills/': typeof DocsSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/api/og'
    | '/docs/brand'
    | '/docs/components'
    | '/docs/skills'
    | '/docs/theming'
    | '/docs/'
    | '/docs/components/$slug'
    | '/docs/skills/$slug'
    | '/docs/components/'
    | '/docs/skills/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/og'
    | '/docs/brand'
    | '/docs/theming'
    | '/docs'
    | '/docs/components/$slug'
    | '/docs/skills/$slug'
    | '/docs/components'
    | '/docs/skills'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/api/og'
    | '/docs/brand'
    | '/docs/components'
    | '/docs/skills'
    | '/docs/theming'
    | '/docs/'
    | '/docs/components/$slug'
    | '/docs/skills/$slug'
    | '/docs/components/'
    | '/docs/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/brand': {
      id: '/docs/brand'
      path: '/brand'
      fullPath: '/docs/brand'
      preLoaderRoute: typeof DocsBrandRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components': {
      id: '/docs/components'
      path: '/components'
      fullPath: '/docs/components'
      preLoaderRoute: typeof DocsComponentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills': {
      id: '/docs/skills'
      path: '/skills'
      fullPath: '/docs/skills'
      preLoaderRoute: typeof DocsSkillsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/': {
      id: '/docs/components/'
      path: '/'
      fullPath: '/docs/components/'
      preLoaderRoute: typeof DocsComponentsIndexRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/components/$slug': {
      id: '/docs/components/$slug'
      path: '/$slug'
      fullPath: '/docs/components/$slug'
      preLoaderRoute: typeof DocsComponentsSlugRouteImport
      parentRoute: typeof DocsComponentsRoute
    }
    '/docs/skills/': {
      id: '/docs/skills/'
      path: '/'
      fullPath: '/docs/skills/'
      preLoaderRoute: typeof DocsSkillsIndexRouteImport
      parentRoute: typeof DocsSkillsRoute
    }
    '/docs/skills/$slug': {
      id: '/docs/skills/$slug'
      path: '/$slug'
      fullPath: '/docs/skills/$slug'
      preLoaderRoute: typeof DocsSkillsSlugRouteImport
      parentRoute: typeof DocsSkillsRoute
    }
  }
}

interface DocsComponentsRouteChildren {
  DocsComponentsSlugRoute: typeof DocsComponentsSlugRoute
  DocsComponentsIndexRoute: typeof DocsComponentsIndexRoute
}

const DocsComponentsRouteChildren: DocsComponentsRouteChildren = {
  DocsComponentsSlugRoute: DocsComponentsSlugRoute,
  DocsComponentsIndexRoute: DocsComponentsIndexRoute,
}

const DocsComponentsRouteWithChildren = DocsComponentsRoute._addFileChildren(
  DocsComponentsRouteChildren,
)

interface DocsSkillsRouteChildren {
  DocsSkillsSlugRoute: typeof DocsSkillsSlugRoute
  DocsSkillsIndexRoute: typeof DocsSkillsIndexRoute
}

const DocsSkillsRouteChildren: DocsSkillsRouteChildren = {
  DocsSkillsSlugRoute: DocsSkillsSlugRoute,
  DocsSkillsIndexRoute: DocsSkillsIndexRoute,
}

const DocsSkillsRouteWithChildren = DocsSkillsRoute._addFileChildren(
  DocsSkillsRouteChildren,
)

interface DocsRouteChildren {
  DocsBrandRoute: typeof DocsBrandRoute
  DocsComponentsRoute: typeof DocsComponentsRouteWithChildren
  DocsSkillsRoute: typeof DocsSkillsRouteWithChildren
  DocsThemingRoute: typeof DocsThemingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsBrandRoute: DocsBrandRoute,
  DocsComponentsRoute: DocsComponentsRouteWithChildren,
  DocsSkillsRoute: DocsSkillsRouteWithChildren,
  DocsThemingRoute: DocsThemingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
