import { defineConfig } from "tsup"

export default defineConfig((options) => ({
  entry: [
    "src/index.ts",
    "src/lib/utils.ts",
    "src/hooks/*.ts",
    "src/components/*.tsx",
  ],
  format: ["esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: !options.watch,
  onSuccess: options.watch
    ? "bun run build:globals && bun run build:fonts"
    : undefined,
  treeshake: true,
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "lucide-react",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "input-otp",
    "react-day-picker",
    "date-fns",
    "d3",
    "d3-sankey",
    "embla-carousel-react",
    "react-resizable-panels",
    "recharts",
    "cmdk",
    "@shadcn/react",
    "sonner",
    "next-themes",
    "motion",
    /^motion\//,
    "@internationalized/date",
    "culori",
    "uqr",
    /^@base-ui\//,
    /^@carsxe\/design-system/,
  ],
}))
